### PR TITLE
Fix interaction of migration windows and configured update check frequency

### LINKED ISSUE #531: Better handle interaction of update windows and check interval
Currently it's possible to define an update window (say, for example daily from 2am - 4am) and the default check interval of six hours will result in IncusOS never actually being able to check for an update _except_ if you happen to have initially booted the system sometime between 2am - 4am.

We should process maintenance windows before sleeping, and then sleep the minimum time of the configured check interval and the next maintenance window (if any).

### PR DESCRIPTION
**Pull request by gibmat**
Closes #531

### CODE REVIEW

File: incus-osd/api/system_update.go [hunk 1]
```diff
@@ -43,8 +43,58 @@ func (w *SystemUpdateMaintenanceWindow) IsCurrentlyActive() bool {
...
+	if endOffset >= 7*24*60 && int(t.Weekday()) <= int(w.EndDayOfWeek.ToWeekday()) {
+		currentPosition += 7 * 24 * 60
+	}
+
+	// Migration window is currently active.
+	if startOffset <= currentPosition && currentPosition <= endOffset {
+		return 0 * time.Minute
+	}
+
+	// Migration window hasn't yet started.'
```
Comment (stgraber) [inline incus-osd/api/system_update.go]: You've got a random `'` here :)

**Review by stgraber — APPROVED** [review]

File: incus-osd/api/system_update.go (hunk 1 above)
Comment (gibmat) [reply incus-osd/api/system_update.go]: Yeah, I wanted to push my WIP yesterday afternoon before taking a bit of a mental break. :slightly_smiling_face:

**Comment by stgraber** [comment]
@gibmat is there more needed or is that good to go?

**Comment by gibmat** [comment]
> @gibmat is there more needed or is that good to go?

Still a little bit of tweaking

**Comment by gibmat** [comment]
@stgraber OK, I think this should be ready now.
